name: Test against different Go versions

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go: [ "1.20.6", "1.19.11" ]
    name: Test against Go ${{ matrix.go }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Run main
        run: |
          go build
